/* One app, two identities.

   APP_VARIANT picks which one. eas.json sets it per build profile; anything
   that does not set it — `expo start`, `expo run:ios`, a local prebuild — falls
   through to staging. That default is deliberate and load-bearing: the failure
   mode of an unmarked build has to be "talks to staging", never "talks to the
   garages' real data".

   The bundle id / package has to differ, not just the Supabase URL, because
   that string is what the device and the stores key off. While both variants
   shared one:
     - a staging build installed over the App Store app on the same phone,
     - and inherited its AsyncStorage Supabase session,
     - and the old `staging-play` profile uploaded a staging-pointed AAB into
       the production Play listing, one promote away from real garages.

   ios/ and android/ are gitignored and regenerated by prebuild on every build,
   so this file is the single source of truth for native identity. */

const VARIANT = process.env.APP_VARIANT === 'production' ? 'production' : 'staging';
const IS_PROD = VARIANT === 'production';

module.exports = {
  expo: {
    // The slug is the EAS project's identity, not the app's — it stays fixed
    // across variants so both keep reporting into the same EAS project.
    slug: 'garage-mobile',
    name: IS_PROD ? 'מוסך' : 'מוסך (Staging)',
    version: '1.0.0',
    orientation: 'portrait',
    icon: './assets/icon.png',
    userInterfaceStyle: 'light',

    // Deep links need splitting for the same reason as the bundle id: two
    // installed apps both claiming `garage://` and the OS resolves it to
    // whichever it feels like.
    scheme: IS_PROD ? 'garage' : 'garage-staging',

    ios: {
      supportsTablet: true,
      bundleIdentifier: IS_PROD
        ? 'com.adam-tsityat.garage-mobile'
        : 'com.adam-tsityat.garage-mobile.staging',
      config: {
        usesNonExemptEncryption: false,
      },
    },

    android: {
      adaptiveIcon: {
        backgroundColor: '#E6F4FE',
        foregroundImage: './assets/android-icon-foreground.png',
        backgroundImage: './assets/android-icon-background.png',
        monochromeImage: './assets/android-icon-monochrome.png',
      },
      predictiveBackGestureEnabled: false,
      package: IS_PROD ? 'com.tsityat.garageapp' : 'com.tsityat.garageapp.staging',
    },

    web: {
      favicon: './assets/favicon.png',
    },

    plugins: [
      'expo-router',
      [
        'expo-image-picker',
        {
          photosPermission: 'כדי לצרף תמונות לכרטיס העבודה, יש לאשר גישה לתמונות.',
          cameraPermission: 'כדי לצלם את הרכב ולצרף לכרטיס העבודה, יש לאשר גישה למצלמה.',
          microphonePermission: false,
        },
      ],
      'expo-status-bar',
    ],

    extra: {
      router: {},
      eas: {
        projectId: '561269a8-1e84-41a9-9ebd-a9cb496afbee',
      },
      // Read back at runtime by lib/env.ts, so the app can say which variant it
      // is and cross-check that against the database it actually reached.
      appVariant: VARIANT,
    },

    owner: 'adam-tsityat',
  },
};
